# general #####

set -g default-shell $SHELL
set -g default-command $SHELL
set -g default-terminal tmux-256color
set -g mouse on
set -g base-index 1


# key bind #####

unbind s
bind a new-session
bind C-r source-file ~/.tmux.conf \; display-message "config reloaded"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L
bind J resize-pane -D
bind K resize-pane -U
bind L resize-pane -R
bind s split-window -v
bind v split-window -h
unbind K
bind K confirm-before "kill-window"
unbind Q
bind Q confirm-before "kill-server"
bind C-k display-popup
bind -n C-f display-popup -E -w 80% -h 60% "tmux-claude"
## copy mode
bind y copy-mode
set -w -g mode-keys vi



# appearance #####

## bell
set -g bell-action any
set -g visual-bell off
set -g monitor-bell on
set -g allow-passthrough on

## status bar
set -g status-style 'fg=#cdd6f4,bg=#1e1e2e'
set -g message-style 'fg=#1e1e2e,bg=#cdd6f4'
set -g status-interval 30
set -g status-position bottom

set -g status-left '#(tmux-sessions)#[fg=#d8dee9]| #[default]'
set -g status-left-length 80
set -g status-right '#{?client_prefix,#[fg=#eba0ac]PREFIX#[fg=#d8dee9] | ,}#{?pane_in_mode,#[fg=#ebcb8b]COPY#[fg=#d8dee9] | ,}#[fg=#d8dee9]%Y-%m-%d (%a) %H:%M '
set -g status-right-length 50

## window status
set -g status-justify left
set -g window-status-format '#{?#{@claude_done},#[fg=#a6e3a1],} #{?window_bell_flag,⚡︎ ,}#{?#{@claude_done},✔︎ ,}#I:#W #[default]'
set -g window-status-current-format '#{?#{@claude_done},#[fg=#a6e3a1],} #{?window_bell_flag,⚡︎ ,}#{?#{@claude_done},✔︎ ,}#I:#W #[default]'
set -g window-status-style 'fg=#6c7086'
set -g window-status-current-style 'fg=#cba6f7,bold'
set -g window-status-bell-style 'fg=#f9e2af'

## pane
set-hook -g after-select-window 'set-window-option @claude_done 0'
set-hook -g pane-focus-in 'set-window-option @claude_done 0'

## pane
set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[bold],}#{pane_index}:#{pane_current_command}"
set -g pane-border-style 'fg=#4c566a'
set -g pane-active-border-style 'fg=#b4befe'
