---
- hosts: localhost
  connection: local

  tasks:
    - name: register ansible runner name
      shell: whoami
      register: user_name

    # initial tasks #############################################
    - name: user setting
      user:
        name: "{{ user_name.stdout }}"
        shell: /usr/local/bin/zsh
      become: yes
      failed_when: False
      tags:
      - initial

    # for VSCodeVim
    # https://github.com/VSCodeVim/Vim#mac
    - name: set up macos defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
        state: "{{ item.state }}"
      loop:
      - domain: com.microsoft.VSCode
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present
      - domain: com.microsoft.VSCodeInsiders
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present
      tags:
      - initial

    - name: check homebrew installed
      shell: type brew
      register: installed_homebrew
      failed_when: False
      tags:
      - initial

    - name: install homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      register: installed_homebrew
      when: installed_homebrew == False
      tags:
      - initial

    - name: install packages from brewfile
      shell: brew bundle
      failed_when: False
      tags:
      - initial

    - name: make directories
      file:
        dest: "{{ item }}"
        owner: "{{ user_name.stdout }}"
        group: admin
        state: directory
      loop:
        - "/Users/{{ user_name.stdout }}/.vim"
        - "/Users/{{ user_name.stdout }}/.vim/rc"
        - "/Users/{{ user_name.stdout }}/.zsh"
        - "/Users/{{ user_name.stdout }}/.config"
        - "/Users/{{ user_name.stdout }}/.gittemplates"
        - "/Users/{{ user_name.stdout }}/.gittemplates/hooks"
      tags:
      - initial

    - name: get git bash completion
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
        dest: $HOME/.zsh/git-completion.bash
        owner: "{{ user_name.stdout }}"
        group: admin
      tags:
      - initial

    - name: get git zsh completion
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
        dest: $HOME/.zsh/_git
        owner: "{{ user_name.stdout }}"
        group: admin
      tags:
      - initial


    # symlinks ##################################################
    - name: make symlinks at HOME
      file:
        src: "{{ item }}"
        dest: "$HOME/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
      with_fileglob:
        - "files/HOME/.*"
      tags:
      - symlinks

    - name: make symlinks for gittemplates
      file:
        src: "{{ item }}"
        dest: "$HOME/.gittemplates/hooks/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
        force: yes
      with_fileglob:
        - "files/HOME/.gittemplates/hooks/*"
      tags:
      - symlinks

    - name: make symlinks for vim
      file:
        src: "{{ item }}"
        dest: "$HOME/.vim/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
        force: yes
      with_fileglob:
        - "files/vim/*"
      tags:
      - symlinks

    - name: make symlinks for dein.vim
      file:
        src: "{{ item }}"
        dest: "$HOME/.vim/rc/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
        force: yes
      with_fileglob:
        - "files/vim/rc/*"
      tags:
      - symlinks

    - name: make symlinks for config
      file:
        src: "{{ item }}"
        dest: "$HOME/.config/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
        force: yes
      with_fileglob:
        - "files/config/*"
      tags:
      - symlinks

    - name: make symlinks for /usr/local/bin
      file:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item.split('/')[-1] }}"
        owner: "{{ user_name.stdout }}"
        state: link
        force: yes
      with_fileglob:
        - "files/bin/*"
      tags:
      - symlinks

    # Python ####################################################
    - name: install virtualenv
      pip:
        name: virtualenv
        executable: pip3
      tags:
      - python

    - name: make virtualenv directory
      file:
        dest: $HOME/.virtualenv
        owner: "{{ user_name.stdout }}"
        state: directory
      tags:
      - python

