[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'colorscheme iceberg'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'choplin/unite-vim_hacks'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'jacquesbh/vim-showmarks'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'glidenote/serverspec-snippets'

[[plugins]]
repo = 'lambdalisue/vim-gista'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'nvie/vim-flake8'

