# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: delta
# Aliases allow you to create nicknames for gh commands
aliases:
    watches: api /users/chroju/subscriptions --paginate --jq .[].full_name
    gitignore: api /gitignore/templates/$1 --jq .source
    unwatch: api -X DELETE /repos/$1/subscription
    search: api -X GET search/repositories -f q="$1" --template "{{range .items}}{{.full_name}} ⭐ {{.stargazers_count | color \"yellow\"}} {{.description | color \"cyan\"}} {{.html_url | color \"white+d\"}}{{\"\\n\"}}{{end}}"
    apply: pr comment --body "atlantis apply"
    myissue: api issues --template  "{{range .}}{{ printf \"%s%s%v\" .repository.full_name \"#\" .number | color \"green\"}} {{.title}} {{.url | color \"white+d\"}}{{\"\\n\"}}{{end}}"
    mypr: api -X GET search/issues -f q='is:pr is:open review-requested:chroju' --template "{{ range .items }}{{ .created_at }} {{ .title | color \"green\" }} ({{ .user.login }}) {{ .html_url | color \"white+d\" }} {{\"\\n\"}}{{ end }}"
    fzf-issues: '!gh issue list -R $1 | fzf-tmux --layout=reverse --preview "gh issue view -R $1 {+1}" | cut -f 1 | pbcopy'
    fzf-myissues: '!gh issue list -a @me -R $1 | fzf-tmux --layout=reverse --preview "gh issue view -R $1 {+1}" | cut -f 1 | pbcopy'
    fzf-pr-co: '!gh pr list | fzf-tmux --preview "gh pr view {+1}" | cut -f 1 | xargs gh pr checkout'
    fzf-pr: '!gh pr list | fzf-tmux --preview "gh pr view {+1}" | cut -f 1 | pbcopy'
    fzf-pr-view: '!gh pr list | fzf-tmux --preview "gh pr view {+1}" | cut -f 1 | xargs gh pr view -c'
    latest: '!gh release list -R $1 | head -n 1'
version: "1"
